spring.application.name=sistema-ventas

# Database configuration for PostgreSQL (Render)
# Using the Internal URL for communicating within Render
spring.datasource.url=jdbc:postgresql://dpg-d5i0php5pdvs73boq1mg-a:5432/sistema_ventas_db
spring.datasource.username=sistema_ventas_db_user
spring.datasource.password=Ls2o5o7ApB1jlwWphlso9HbZ1MWBOGGQ
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Initial SQL import (Runs import.sql to seed data)
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:import.sql
spring.jpa.defer-datasource-initialization=true

# Uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
