# Configuración para Base de Datos Local
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_ventas_db
spring.datasource.username=postgres
# REEMPLAZA ESTO por la contraseña que pusiste al instalar PostgreSQL en tu PC
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Desactivar carga automática de archivos
spring.sql.init.mode=never
